name : Compile and run test
run-name : For ${{ github.actor }} compiling and running and test
on : [push]
jobs : 
  compile :
    runs-on : ubuntu-latest
    steps :
      - name : checkout code
        uses : actions/checkout@v4
      - name : setup environment 
        uses : actions/setup-python@v2
        with :
          python-version : 3.8
      - name : Run python script
        run : |
          python3 -m hello-world/hello.py
